---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nr-pvc
  namespace: node-red
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-1